### ISSUE TITLE
What technology and architecture are we going to use?

### ISSUE THREAD

**Issue by nramirez** [nramirez/SmartForm#1]
As we talked we are going to build a C# application, maybe using the Hexagonal Architecture just like @mamodom suggested more details here http://fideloper.com/hexagonal-architecture.

We have to define the following:
* Are we going to use BDD + unit tests, or only unit tests or only BDD?
* Are we going to use Specflow?
* Which framework are we going to use?
* Are we going to use InMemory database, or are we going to create our own InMemory structure?

Let's decide what are we going to use server side, later we decide what to use in the front end.
If I'm missing something important to define at this beginning please let me know.

**Comment by nramirez** [comment]
This is what I propose: 
-Hexagonal Architecture (http://fideloper.com/hexagonal-architecture)
-.Net Framework 4.5.1
-BDD with Specflow 
-If we nee to mock something we could use NSubstitude (http://nsubstitute.github.io/help/getting-started/)
-Use Effort for the InMemory Database. (https://effort.codeplex.com/)

**Comment by eatskolnikov** [comment]
@nramirez  i couldnt agree more.

**Comment by mamodom** [comment]
I'm not used to mocking frameworks but this could be a nice opportunity to get familiarized them. I rather  create fakes and tests doubles.
Same thing applies with Effort, I'm used to create fakes.
Regarding SpecFlow I could give you guys some insights.

**Comment by nramirez** [comment]
Cool! This way everyone will learn something new! :+1:
