### ISSUE TITLE
Entities Definition

### ISSUE THREAD

**Issue by nramirez** [nramirez/SmartForm#4]
We were talking that the system will basically have two parts:

- The Form System which will allow the users to create the questionaries, something like google forms.
- And the Quality System that will be the process/algorithm that will have the logic and will identify the irregularities based on a created questionaries, this will be explained better in the readme.

First of all, Let's define the structure of the Form System, I think that would be something like this:
- User (We would be managing this with the Identity)
-- Name

- Form
-- Name
-- Description
-- UserId
-- Collection of Questions

- Questions
-- Name
-- Description (This would be optional, we will maybe display it using a tooltip or something similar)
-- Collection of Answers
-- FormId
-- Type (Answer would be multiple choices or single option)*

- Answers
-- Name
-- Description
-- QuestionId

*When the type is 'Multiple Choices' the answers will appear with checkboxes, and for the 'Single Option' we can use a dropdown or radio button to construct the form. Then We would have three options: Multiple, Single Radio and Single Dropdown.

Is this structure ok? Did I miss something?

**Comment by eatskolnikov** [comment]
It looks great and simple. I could come up with a question like:
Should the user be able to use questions in other forms?

But let's keep it simple, this looks good enough for me.

**Comment by Edulopez** [comment]
If we re only analize fixed answers is ok for me. I think it's better this way, following the KISS Principle in the first steps of the project. Later on we could add free answers (text) to the questions.

**Comment by nramirez** [comment]
Great! We all agree about keeping it simple. :)
